app:
  name: doudou
  port: 8090
  version: 1.0.0
request:
  timeout: 40000
os:
  write: /workspaces/ceshi/write
  read: /workspaces/ceshi/read
  reqwrite: /workspaces/ceshi/reqwrite
  reqread: /workspaces/ceshi/reqread


